#!/usr/bin/env node
// Downloads the brand fonts from Google Fonts into assets/fonts/ and writes assets/fonts.css.
// Run once (fonts are committed, so you normally never need this): node fetch-fonts.js
const fs = require('fs');
const path = require('path');

const FAMILIES = [
  'Montserrat:wght@700;800;900',
  'Oswald:wght@500;700',
  'Inter:wght@400;500;600;700',
  'Caveat:wght@700',
];
const UA = 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0 Safari/537.36';
const dir = path.join(__dirname, 'assets', 'fonts');

(async () => {
  fs.mkdirSync(dir, { recursive: true });
  const url = 'https://fonts.googleapis.com/css2?' + FAMILIES.map(f => 'family=' + f).join('&') + '&display=swap';
  const css = await (await fetch(url, { headers: { 'User-Agent': UA } })).text();
  // keep only latin + latin-ext subsets (Turkish lives in latin-ext)
  const blocks = [...css.matchAll(/\/\*\s*([a-z-]+)\s*\*\/\s*(@font-face\s*\{[^}]*\})/g)];
  let out = '/* Generated by fetch-fonts.js — Google Fonts, SIL Open Font License */\n';
  let n = 0;
  for (const [, subset, b] of blocks) {
    if (subset !== 'latin' && subset !== 'latin-ext') continue;
    const family = b.match(/font-family:\s*'([^']+)'/)[1];
    const weight = b.match(/font-weight:\s*(\d+)/)[1];
    const src = b.match(/url\(([^)]+)\)/)[1];
    const file = `${family.replace(/\s+/g, '')}-${weight}-${subset}.woff2`;
    const buf = Buffer.from(await (await fetch(src, { headers: { 'User-Agent': UA } })).arrayBuffer());
    fs.writeFileSync(path.join(dir, file), buf);
    out += b.replace(/url\([^)]+\)/, `url(fonts/${file})`) + '\n';
    n++;
  }
  fs.writeFileSync(path.join(__dirname, 'assets', 'fonts.css'), out);
  console.log(`Saved ${n} font files to assets/fonts/ and wrote assets/fonts.css`);
})().catch(e => { console.error(e); process.exit(1); });
