import { NextRequest, NextResponse } from "next/server";
import { auth } from "@/lib/auth";
import { db } from "@/lib/db";

export async function POST(
  _req: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  const session = await auth();
  if (!session) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  const { id } = await params;

  try {
    // Get session with transcript and participants
    const speakingSession = await db.speakingSession.findUnique({
      where: { id },
      include: {
        transcript: true,
        participants: {
          include: { student: { select: { id: true, name: true } } },
        },
        sourceLesson: { select: { title: true, topics: true, content: true } },
      },
    });

    if (!speakingSession) {
      return NextResponse.json(
        { error: "Session not found" },
        { status: 404 }
      );
    }

    if (!speakingSession.transcript) {
      return NextResponse.json(
        { error: "No transcript uploaded. Upload a transcript first." },
        { status: 400 }
      );
    }

    // Delete existing analyses for re-analysis
    await db.sessionAnalysis.deleteMany({ where: { sessionId: id } });

    // Generate analysis per student
    // In production this would call the AI cascade (Gemini Flash -> Claude Haiku)
    // For now, create structured analysis entries based on transcript
    const transcriptContent = speakingSession.transcript.content;
    const lessonContext = speakingSession.sourceLesson
      ? `Lesson: ${speakingSession.sourceLesson.title}. Topics: ${speakingSession.sourceLesson.topics || "N/A"}`
      : null;

    const analyses = [];
    for (const participant of speakingSession.participants) {
      const studentName = participant.student.name;

      // Determine participation based on name mentions in transcript
      const nameCount = (
        transcriptContent.match(new RegExp(studentName, "gi")) || []
      ).length;
      const participationScore = Math.min(10, Math.max(1, nameCount * 2));

      const analysis = await db.sessionAnalysis.create({
        data: {
          transcriptId: speakingSession.transcript.id,
          sessionId: id,
          studentId: participant.studentId,
          summary: `${studentName} participated in the speaking session on "${speakingSession.topic}". ${
            lessonContext
              ? `The session was based on a classroom lesson covering: ${speakingSession.sourceLesson?.topics || speakingSession.sourceLesson?.title}.`
              : ""
          } Analysis pending AI processing.`,
          vocabularyUsed:
            "Vocabulary analysis will be generated by AI based on transcript content.",
          grammarNotes:
            "Grammar patterns and error analysis will be generated by AI.",
          pronunciationNotes: null,
          participationScore,
          strengths:
            "Strengths assessment will be provided after full AI analysis.",
          areasToImprove:
            "Improvement areas will be identified after full AI analysis.",
          homework: null,
        },
      });
      analyses.push(analysis);

      // Create teacher insight for this student
      await db.teacherInsight.create({
        data: {
          teacherId: session.user.id,
          studentId: participant.studentId,
          sessionId: id,
          type: "recommendation",
          content: `Speaking session analysis completed for "${speakingSession.topic}". Participation score: ${participationScore}/10.`,
          priority:
            participationScore >= 7
              ? "low"
              : participationScore >= 4
                ? "medium"
                : "high",
        },
      });
    }

    // Mark transcript as analyzed
    await db.sessionTranscript.update({
      where: { id: speakingSession.transcript.id },
      data: { analyzedAt: new Date() },
    });

    // Update session status to completed if it was scheduled
    if (speakingSession.status === "scheduled" || speakingSession.status === "in_progress") {
      await db.speakingSession.update({
        where: { id },
        data: { status: "completed" },
      });
    }

    return NextResponse.json({
      message: "Analysis complete",
      analysesCount: analyses.length,
    });
  } catch (error) {
    console.error("Failed to run analysis:", error);
    return NextResponse.json(
      { error: "Failed to run analysis" },
      { status: 500 }
    );
  }
}
